version: 2
jobs:
  build:
    docker:
    - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: Install Node Dependencies
        command: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test
    - deploy:
        name: Expo Deployment
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn semantic-release
          fi
workflows:
  version: 2
  workflow:
    jobs:
    - build
