# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Node Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - deploy:
          name: Expo Deployment
          command: |
            TERM=dumb
            ROOT_BRANCH="master"
            if [ "${CIRCLE_BRANCH}" == $ROOT_BRANCH ]; then
                echo " ▶️  Deploying on ${CIRCLE_BRANCH}. Continuing the job..."
                # yarn semantic-release
                npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
                npx expo publish
            fi
